# Uncomment the next line to define a global platform for your project
platform :osx, '10.9'

target 'DMOnlineDrawingBoard(Server)' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DMOnlineDrawingBoard(Server)
pod 'Protobuf', '~> 3.4.0'
pod 'Masonry', '~> 1.0.2'
pod 'CocoaAsyncSocket', '~> 7.6.1'
end
