// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: drawingboard.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "Drawingboard.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - DrawingboardRoot

@implementation DrawingboardRoot

// No extensions in the file and no imports, so no need to generate
// +extensionRegistry.

@end

#pragma mark - DrawingboardRoot_FileDescriptor

static GPBFileDescriptor *DrawingboardRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@""
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - DMPoint

@implementation DMPoint

@dynamic x;
@dynamic y;
@dynamic scaleX;
@dynamic scaleY;
@dynamic boardW;
@dynamic boardH;

typedef struct DMPoint__storage_ {
  uint32_t _has_storage_[1];
  float x;
  float y;
  float scaleX;
  float scaleY;
  float boardW;
  float boardH;
} DMPoint__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "x",
        .dataTypeSpecific.className = NULL,
        .number = DMPoint_FieldNumber_X,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(DMPoint__storage_, x),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeFloat,
      },
      {
        .name = "y",
        .dataTypeSpecific.className = NULL,
        .number = DMPoint_FieldNumber_Y,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(DMPoint__storage_, y),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeFloat,
      },
      {
        .name = "scaleX",
        .dataTypeSpecific.className = NULL,
        .number = DMPoint_FieldNumber_ScaleX,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(DMPoint__storage_, scaleX),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeFloat,
      },
      {
        .name = "scaleY",
        .dataTypeSpecific.className = NULL,
        .number = DMPoint_FieldNumber_ScaleY,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(DMPoint__storage_, scaleY),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeFloat,
      },
      {
        .name = "boardW",
        .dataTypeSpecific.className = NULL,
        .number = DMPoint_FieldNumber_BoardW,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(DMPoint__storage_, boardW),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeFloat,
      },
      {
        .name = "boardH",
        .dataTypeSpecific.className = NULL,
        .number = DMPoint_FieldNumber_BoardH,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(DMPoint__storage_, boardH),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeFloat,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[DMPoint class]
                                     rootClass:[DrawingboardRoot class]
                                          file:DrawingboardRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(DMPoint__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\004\003\006\000\004\006\000\005\006\000\006\006\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - DMStroke

@implementation DMStroke

@dynamic pointsArray, pointsArray_Count;

typedef struct DMStroke__storage_ {
  uint32_t _has_storage_[1];
  NSMutableArray *pointsArray;
} DMStroke__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "pointsArray",
        .dataTypeSpecific.className = GPBStringifySymbol(DMPoint),
        .number = DMStroke_FieldNumber_PointsArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(DMStroke__storage_, pointsArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[DMStroke class]
                                     rootClass:[DrawingboardRoot class]
                                          file:DrawingboardRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(DMStroke__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - DMPaint

@implementation DMPaint

@dynamic strokesArray, strokesArray_Count;

typedef struct DMPaint__storage_ {
  uint32_t _has_storage_[1];
  NSMutableArray *strokesArray;
} DMPaint__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "strokesArray",
        .dataTypeSpecific.className = GPBStringifySymbol(DMStroke),
        .number = DMPaint_FieldNumber_StrokesArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(DMPaint__storage_, strokesArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[DMPaint class]
                                     rootClass:[DrawingboardRoot class]
                                          file:DrawingboardRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(DMPaint__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
