// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: drawingboard.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class DMPoint;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - DrawingboardRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface DrawingboardRoot : GPBRootObject
@end

#pragma mark - DMPoint

typedef GPB_ENUM(DMPoint_FieldNumber) {
  DMPoint_FieldNumber_X = 1,
  DMPoint_FieldNumber_Y = 2,
};

@interface DMPoint : GPBMessage

@property(nonatomic, readwrite) float x;

@property(nonatomic, readwrite) float y;

@end

#pragma mark - DMStroke

typedef GPB_ENUM(DMStroke_FieldNumber) {
  DMStroke_FieldNumber_PointsArray = 1,
};

@interface DMStroke : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<DMPoint*> *pointsArray;
/** The number of items in @c pointsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger pointsArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
